version: '3'

services:

  redis-a:
    image: redis:6.2-alpine
    container_name: redis-a
    network_mode: "host"
    restart: always
    ports:
      - "${REDIS_A_PORT}:6379"
    volumes: 
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  sentinel-a:
    image: redis:6.2-alpine
    container_name: sentinel-a
    network_mode: "host"
    restart: always
    command: sh -c "chown redis:redis -R /etc/redis && redis-server /etc/redis/sentinel.conf --sentinel"
    depends_on:
      - redis-a
    ports:
      - "${SENTINEL_A_PORT}:26379"
    volumes: 
      - ./data:/etc/redis
